name: PostgreSQL Setup

on:
  workflow_dispatch:  # Разрешает ручной запуск
  push:              # Автозапуск при push
    branches: [ main ]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Set up PostgreSQL
        uses: harmon758/postgresql-action@v1.0.0
        with:
          postgresql_version: '17.5'
          dbname: ${{ secrets.DB_NAME }}
          username: ${{ secrets.DB_USERNAME }}
          password: ${{ secrets.DB_PASSWORD }}
